BaseException: Added accessor methods for message type in BaseException. SandboxException: Added second input argument Gmat::MessageType mt = Gmat::ERROR_ to constructor Sandbox: When FCS is NULL, SandboxException is created with message type of Gmat::GENERAL_ so function error count is not repeated in the message. (Bug 2272 fix)